In [5]:
# Read the emails file
import pandas as pd

dataset = pd.read_excel("output_tfidf_clustering_with_custom_keywords.xlsx")

In [9]:
dataset.describe()

,replace sim,my existing sim,existing sim,my old sim,old sim,replacement of sim,replace my old sim card,replace old sim card,replace old sim,sim card,...,request new,mobile numbers,international minutes,add ons,activate sim,new business,business ultimate,roaming data,cancel account,months contract
count,9772.000000,9772.0,9772.000000,9772.0,9772.000000,9772.000000,9772.0,9772.0,9772.0,9772.000000,...,9772.000000,9772.000000,9772.000000,9772.000000,9772.000000,9772.000000,9772.000000,9772.000000,9772.000000,9772.000000
mean,0.002558,0.0,0.004503,0.0,0.001944,0.003070,0.0,0.0,0.0,0.198015,...,0.001330,0.018829,0.027323,0.008084,0.005628,0.023434,0.028449,0.013201,0.003070,0.027323
std,0.050518,0.0,0.066954,0.0,0.044054,0.055325,0.0,0.0,0.0,0.398524,...,0.036451,0.135929,0.163031,0.089553,0.074815,0.151286,0.166259,0.114140,0.055325,0.163031
min,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,0.0,1.000000,0.0,1.000000,1.000000,0.0,0.0,0.0,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [4]:
sim_repl_dataset = dataset[(dataset['replace sim'] == 1) | 
                           (dataset['my existing sim'] == 1) |
                           (dataset['existing sim'] == 1) | 
                           (dataset['my old sim'] == 1) |
                           (dataset['old sim'] == 1)|
                           (dataset['replacement of sim'] == 1) | 
                           (dataset['replace my old sim card'] == 1) |
                           (dataset['replace old sim'] == 1) |
                           (dataset['replacement sim'] == 1) |
                           (dataset['replacement sim card'] == 1) |
                           (dataset['sim replacement'] == 1)
                          ]

KeyError: 'replace my old sim'

In [27]:
sim_repl_dataset.describe()

,sim card,mobile number,account number,replacement sim,immediate effect,sim cards,new sim,local data,data roaming,replacement sim card,...,request new,mobile numbers,international minutes,add ons,activate sim,new business,business ultimate,roaming data,cancel account,months contract
count,598.000000,598.000000,598.000000,598.000000,598.000000,598.00000,598.000000,598.000000,598.000000,598.000000,...,598.0,598.000000,598.000000,598.0,598.000000,598.000000,598.000000,598.0,598.0,598.000000
mean,0.607023,0.162207,0.075251,0.804348,0.005017,0.06689,0.122074,0.040134,0.011706,0.481605,...,0.0,0.006689,0.016722,0.0,0.006689,0.016722,0.003344,0.0,0.0,0.006689
std,0.488821,0.368950,0.264016,0.397034,0.070710,0.25004,0.327645,0.196437,0.107648,0.500080,...,0.0,0.081580,0.128337,0.0,0.081580,0.128337,0.057783,0.0,0.0,0.081580
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000
25%,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000
50%,1.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000
75%,1.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1.000000,...,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,...,0.0,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,0.0,0.0,1.000000

In [28]:
writer = pd.ExcelWriter('output.xlsx')
sim_repl_dataset.to_excel(writer,'Sheet1')
writer.save()